### ISSUE TITLE
Plugin fails if toolbar: false -> Cannot read property 'controls' of undefined

### ISSUE THREAD

**Issue by oller** [Artem-Schander/quill-paste-smart#10]
The README implies you can specify your own formatting preferences, instead of toolbar, however in my instance i'm hiding the toolbar with `toolbar: false` in the modules.

This then throws an error on paste as in the plugin assumes the module toolbars will be present.

`Cannot read property 'controls' of undefined`

Example sandbox (paste some text):

https://codesandbox.io/s/react-quill-quill-paste-smart-forked-wxl2g?file=/src/App.js

**Comment by artem-schander** [comment]
Hi @oller,
Thank you for raising this issue. I'll look into it in a few hours.

**Comment by oller** [comment]
Cool thanks for the plugin @Artem-Schander! It' looks like just a one-liner around https://github.com/Artem-Schander/quill-paste-smart/blob/master/src/module.js#L70

I'll raise a quick PR, but feel free to edit to your requirements.

**Comment by artem-schander** [comment]
Nice. Thanks.

**Comment by artem-schander** [comment]
@oller 
Thank you for your contribution. 
The fix is now published. [v1.3.1](https://www.npmjs.com/package/quill-paste-smart/v/1.3.1)
