### ISSUE TITLE
Possible to limit the images someone can paste?

### ISSUE THREAD

**Issue by kodeschooler** [Artem-Schander/quill-paste-smart#12]
Hi, I started using this recently and it's excellent. But I'm running into a frustrating problem. In one of my many pages that use this library, I need to have a button that simply inserts a small local image into the editor. I think I'm simply using 
`quill.clipboard.dangerouslyPasteHTML("<img src=/myimage.png />") `

I was told other than in this one case, we cannot allow images to be pasted. When I took out 'img' from the allowed list, this no longer works. It inserts it, but then when I read the text out of the editor, the image string is gone. I understand this is by design. But is there any way for me to allow an exception or to further refine the criteria? For example, a way to allow only an image with a special class or id or something in order to whitelist it, but otherwise not allow other images. Or is it all images or no images?.  Is there any middle ground? Like if I could combine items in the allowed list to allow more refinement in what is excluded? eg: allowed: ['b', 'strong', 'img[id=myimage]'].... something along those lines.

Thanks

**Comment by artem-schander** [comment]
Hi @kodeschooler 

for now it is not possible to filter valid tags by existing props and I think not that it can be done with the used library. [see docs](https://github.com/cure53/DOMPurify#can-i-configure-dompurify).

could you please provide a codesandbox with said button? maybe there is another solution.

**Comment by artem-schander** [comment]
Hi @kodeschooler,

I thought about your issue and had an idea how you possibly could work around it.
To be honest I don't really understand what you mean by
> when I read the text out of the editor, the image string is gone.

I assume, after you pasted the image by `dangerouslyPasteHTML` you go on copying it and pasting it again from your clipboard.

However. 
I've added [sanitizer hooks](https://github.com/cure53/DOMPurify#hooks) of the underlying lib [DOMPurify](https://github.com/cure53/DOMPurify) to the [lates release](https://www.npmjs.com/package/quill-paste-smart/v/1.4.0). They are not that easy to use and it is possible to mess things up.

Feel free to reopen this issue if you feel like it :)

**Comment by kodeschooler** [comment]
Hi, thanks for your reply. I actually fooled myself into thinking what I stated above was true. This morning I realized it works fine, it was something else going on on my screen that led me to believe it was happening. I should close this thread. Thanks for your library!
