### ISSUE TITLE
substituteBlockElements feature destroys attributes even on permitted blocks, breaking copy/paste for checklists

### ISSUE THREAD

**Issue by jwhiting** [Artem-Schander/quill-paste-smart#14]
If you are pasting, for example, the HTML content `<ul data-checked="true"><li>todo item</li></ul>` and have enabled `ul` and `li` tags and the `data-checked` attributes, it should paste as-is. However, what happens is the `data-checked` attribute is lost. I've identified this happens when `substituteBlockElements` option is set to true. Looking at the code, I'm not sure why, but it seems to go through the DOM and replace all block elements with new replacements, but those replaced items do not have the attributes copied over.

The end result is that this module currently breaks copy/paste for lists of type `check`, which is a core feature of Quill.

A proposed solution would be to use the config object to see what attributes are permitted and copy the values of those attributes in this DOM node recreation step. However, I was unsure why this node replacement is happening in the first place even for whitelisted block tags, so I don't feel confident changing the code for a PR. Also, the module attempts to auto-configure itself and should ideally detect the presence of checklists in the toolbar config as well. Thanks for any help/insights.

**Comment by artem-schander** [comment]
Hi @jwhiting,
thank you for raising this issue.
You're right about the replacement for allowed block type nodes, that should not happen.
A PR would be highly appreciated. Otherwise I'll fix it by myself as soon as I can.

**Comment by artem-schander** [comment]
@jwhiting
Thank you for the contribution.
I just published the patch. See [version 1.4.6](https://www.npmjs.com/package/quill-paste-smart/v/1.4.6)

**Comment by jwhiting** [comment]
@Artem-Schander thank you. Glad I could help.

**Comment by jwhiting** [comment]
Oops actually @Artem-Schander I didn't realize I should have updated the build asset in the PR. The new version doesn't contain the updated code in dist/. Will you build and redeploy when you get a chance?

**Comment by artem-schander** [comment]
Oh. I didn't think of that either. NPM won't let me unpublish because of dependents, so I had to to publish a [new patch](https://www.npmjs.com/package/quill-paste-smart/v/1.4.7).
