### ISSUE TITLE
Problem with paste mention.

### ISSUE THREAD

**Issue by VictorPulzz** [Artem-Schander/quill-paste-smart#17]
Hello!
Can you help me with problem.
After I select mention
![image](https://user-images.githubusercontent.com/23406402/125047131-55e28180-e0a7-11eb-87a8-c196c0faf8f1.png)
And paste this, I got this issue
![image](https://user-images.githubusercontent.com/23406402/125047185-64309d80-e0a7-11eb-835a-ed3e8aee8ea3.png)
When I disable import this plugin, this error did not appear.
I use:
"vue-quill-editor": "^3.0.6",
"quill-mention": "^3.0.3",
"quill-paste-smart": "^1.4.8",

**Comment by artem-schander** [comment]
Hi @VictorPullzz,
sorry for the late reply.
I'll try to reproduce the issue today evening.

**Comment by artem-schander** [comment]
Hi @VictorPulzz I have no Idea if this is still an issue of yours and I'm really sorry that i took that long (I'm working too much).
However this one is solved. The fix will be released in v1.4.10.

**Comment by artem-schander** [comment]
Thanks for your patience. The fix for this issue [is released now](https://www.npmjs.com/package/quill-paste-smart/v/1.4.10).

**Comment by VictorPulzz** [comment]
Thanks @Artem-Schander for you job!)
