### ISSUE TITLE
Header Formats not recognized

### ISSUE THREAD

**Issue by jpdigital** [Artem-Schander/quill-paste-smart#2]
Our Quill Configuration looks like this:

```
[
    ["bold", "italic", "strike", "link"],
    [{ header: [3, 4, 5, 6, false] }],
    ["blockquote", "code-block"],
    [{ list: "bullet" }, { list: "ordered" }]
  ]
```

As you can see we are only allowing `h3` to `h6` to be used because `h1` and `h2` are used in the design of our site. Unfortunately  the header configuration is not parsed by quill-paste-smart and `h3` etc are removed from parsed text. I think this is because the configuration is an array and not an literal.

**Comment by artem-schander** [comment]
Hi @jpdigital,

Thanks for reporting this issue. I‘ll look into it in a few hours.

**Comment by artem-schander** [comment]
Please check out v1.0.5

**Comment by jpdigital** [comment]
Works as expected. Thanks for fixing this so quickly.
