### ISSUE TITLE
quill scroll to top while onPaste triggered

### ISSUE THREAD

**Issue by YangChen00** [Artem-Schander/quill-paste-smart#22]
When I paste content into the quill, the quill will jump to the top of the page, I found that after this line of code is removed, the logic is back to normal, I would like to understand, what is the cause of this problem?

![image](https://user-images.githubusercontent.com/94821645/148715598-59328d4c-73dd-4751-b5dd-1d3a67c2bfcb.png)

**Comment by artem-schander** [comment]
Hi @YangChen00 thank you for raising this issue.
Please excuse me for replying so late. I didn't notice this issue.
I'll take a look at it and remove this line if it's dispensable.

**Comment by YangChen00** [comment]
Not a big problem, thanks for the reply ha

**Comment by artem-schander** [comment]
Hi @YangChen00 
this one should be fixed. Maybe you could try if the issue occurs with `this.quill.scrollIntoView();` instead of `this.quill.container.scrollIntoView();`.
I think I'll release this fix with a few others today evening within v1.4.10

**Comment by artem-schander** [comment]
Thanks for your patience. The fix for this issue [is released now](https://www.npmjs.com/package/quill-paste-smart/v/1.4.10).
