### ISSUE TITLE
Italic format doesn't include 'em'

### ISSUE THREAD

**Issue by helolizbarlow** [Artem-Schander/quill-paste-smart#23]
For the italics case, only `i` is included, and `em` isn't - Quill uses `em` for Italics, so when I try to copy/paste between quill instances when using quill-paste-smart, italics are removed.

Please could you add `em` here: https://github.com/Artem-Schander/quill-paste-smart/blob/39c5f09aeddaaec2ae590fef64f5519009b98684/src/module.js#L141

Thanks!

**Comment by artem-schander** [comment]
Hi @lizcoyote thank you for raising this issue.
Give me a few hours.

**Comment by artem-schander** [comment]
Thanks for your patience. The fix for this issue [is released now](https://www.npmjs.com/package/quill-paste-smart/v/1.4.10).
