### ISSUE TITLE
Add this module on Vue 3

### ISSUE THREAD

**Issue by Julian367** [Artem-Schander/quill-paste-smart#24]
Hello, 

How you can register this module on vue 3?

**Comment by artem-schander** [comment]
Hi @Julian367,
for now I have no idea. I'll take a look as soon as I can.
In case you're quicker, let me know how you did it :)

**Comment by artem-schander** [comment]
There should be nothing different than with v2. Just import it and you're ready to go.
```javascript
import Quill from 'quill';
import 'quill-paste-smart';
```
