### ISSUE TITLE
[BUG] The module makes applications vulnerable to XSS

### ISSUE THREAD

**Issue by skynetigor** [Artem-Schander/quill-paste-smart#28]
**Steps to reproduce**:
1. Open [https://stackblitz.com/edit/angular-cgjqzf?file=src%2Fmain.ts](https://stackblitz.com/edit/angular-cgjqzf?file=src%2Fmain.ts)
2. Copy and Paste `<img src='x' onerror='javascript:alert("XSS !" + location.href)' />` into Quill editor
3. The alert will open although it shouldn't.

I assume this issue exists due to the fact that in the source code assigning of innerHTML is used. In quill editor it appears as expected so pasted text with HTML is displayed as plain text.

NOTE: If you comment out import `import 'quill-paste-smart';` after pasting malicious img tag it does not open the alert.

**Comment by artem-schander** [comment]
@skynetigor 
Thank you for raising this issue. I'll try to find some time and fix it.

**Comment by artem-schander** [comment]
Thanks for your patience. This issue should be resolved now. You need to install [v1.4.12](https://www.npmjs.com/package/quill-paste-smart/v/1.4.12)
