### ISSUE TITLE
How to use this module with plain javascript ?

### ISSUE THREAD

**Issue by tfilo** [Artem-Schander/quill-paste-smart#3]
Hello, I use Quill editor with plain javascript using script tag. 

<script src="js/quill-1.3.7.min.js"></script>

Than I can create new instance of quill editor by calling new Quill(...) but I struggle to use this your module same way. Is it possible insert it into webpage using <script> tag same way as Quill works ? Without need for npm ?  Thank you.

**Comment by artem-schander** [comment]
Hi @tfilo 

thanks for creating an issue.
It should be possible with the [js file from the dist folder](https://github.com/Artem-Schander/quill-paste-smart/blob/master/dist/quill-paste-smart.js).
I didn't thought that there are still people using common js. I'll try to figure out a way in a few hours and add it to the readme.
I'll keep you posted.

**Comment by tfilo** [comment]
Thanks for quick response. I use it with spring-boot application with thymeleaf framework. I don't use npm or any other package manager for javascript in this particular project. I tried js file from dist folder.

<script src="quill-paste-smart.js"></script>
but after that when I try

<script>
  Quill.register('modules/clipboard', PasteSmart, true);
</script>

I get error in browser javascript console:

Uncaught ReferenceError: PasteSmart is not defined
    at add:39

**Comment by artem-schander** [comment]
This one should be solved now. You can either download the [index.js](https://raw.githubusercontent.com/Artem-Schander/quill-paste-smart/master/dist/index.js) or use the [unpkg.com link](https://unpkg.com/quill-paste-smart@latest/dist/index.js).
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Quill Paste Smart</title>
    <link href="https://unpkg.com/quill@latest/dist/quill.snow.css" rel="stylesheet">
</head>
<body>
    <div id="editor"></div>

    <script src="https://unpkg.com/quill@latest/dist/quill.js"></script>
    <script src="https://unpkg.com/quill-paste-smart@latest/dist/index.js"></script>

    <script>
        Quill.register('modules/clipboard', QuillPasteSmart);
        var quill = new Quill('#editor', {
            theme: 'snow',
        });
    </script>
</body>
</html>
```

**Comment by tfilo** [comment]
Thank you, it works well.
